#Sat Jan 04 13:22:00 UTC 2025
micronaut:
  application:
    name: Portfolio Simulator
    aop:
      enabled: true

  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_SECRET:pleaseChangeThisSecretForANewOne}"'
              jws-algorithm: HS256




datasources:
  default:
    url: jdbc:postgresql://localhost:5432/Portfolio_Simulator
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USER:prakhar}
    password: ${JDBC_USER:prakhar}
    pool:
      enabled: true
      maxSize: 10