#Sat Jan 04 13:22:00 UTC 2025
micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_SECRET:pleaseChangeThisSecretForANewOne}"'
              jws-algorithm: HS256
        generator:
          access-token:
            expiration: 3600
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    intercept-url-map:
      - pattern: /auth/**
        access:
          - isAnonymous()



#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/Portfolio_Simulator
#    driverClassName: org.postgresql.Driver
#    username: ${JDBC_USER:prakhar}
#    password: ${JDBC_PASSWORD:prakhar}

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/Portfolio_Simulator
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USER:prakhar}
    password: ${JDBC_USER:prakhar}