#Sat Jan 04 13:22:00 UTC 2025
micronaut:
  application:
    name: Portfolio Simulator
    aop:
      enabled: true

  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_SECRET:pleaseChangeThisSecretForANewOne}"'
              jws-algorithm: HS256


http:
  client:
    read-timeout: 30s
    connection-pool:
      max-pending-requests: 50
      enabled: true
    event-loop-group:
      num-threads: 8
    reactive:
      enabled: true


datasources:
  default:
    url: jdbc:postgresql://localhost:5432/PortfolioSimulator
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USER:prakhar}
    password: ${JDBC_USER:prakhar}
    pool:
      enabled: true
      maxSize: 10