#Sat Jan 04 13:22:00 UTC 2025
micronaut:
  application:
    name: Portfolio Simulator
    aop:
      enabled: true

  server:
    cors:
      enabled: true # Enable CORS
      allowed-origins: # List of allowed origins
        - "http://localhost:5500" # Important: Match your frontend's origin!
        - "http://127.0.0.1:5500" # If needed for other local setups
      allowed-methods: # Allowed HTTP methods
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS # Important for preflight requests
      allowed-headers: # Allowed headers in the request
        - Content-Type
        - Authorization
      allow-credentials: true # If you need to send cookies or authorization headers
      max-age: 3600 # Cache preflight response for 1 hour (optional)

  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_SECRET:pleaseChangeThisSecretForANewOne}"'
              jws-algorithm: HS256


http:
  client:
    read-timeout: 60s
    connection-pool:
      max-pending-requests: 50
      enabled: true
    event-loop-group:
      num-threads: 8
    reactive:
      enabled: true


#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/Portfolio_Simulator
#    driverClassName: org.postgresql.Driver
#    username: ${JDBC_USER:prakhar}
#    password: ${JDBC_USER:prakhar}
#    pool:
#      enabled: true
#      maxSize: 10

datasources:
  default:
    url: jdbc:postgresql://ep-steep-glitter-a1l6rb26-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: npg_9Bg6fVYiJyDz
    dialect: POSTGRES



apis:
  suggestions:
    url: 'https://auto-complete-flrm.onrender.com'
    path: '/autocomplete'
